version: '3.8'

services:
  api:
    build: .
    container_name: purplle_store_intelligence
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
